### ISSUE TITLE
Spigot 1.8.3 can't load Dynmap-Worldguard

### ISSUE THREAD

**Issue by Telbaru** [webbukkit/Dynmap-WorldGuard#29]
Hello,
every time i started the testserver with the newest version of spigot:

[10:27:13] [Server thread/ERROR]: Could not load 'plugins\Dynmap-WorldGuard-0.80.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldGuard
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]

Version:
This server is running CraftBukkit version git-Spigot-dbe012b-61ef214 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Dynmap:
[10:27:16] [Server thread/INFO]: [dynmap] Loading dynmap v2.1-SNAPSHOT-1077
[10:27:16] [Server thread/INFO]: [dynmap] version=git-Spigot-dbe012b-61ef214 (MC: 1.8.3)
[10:27:16] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[10:27:16] [Server thread/INFO]: [dynmap] Mod Support API available

Greeting
Telbaru

**Comment by gerardvanschip** [comment]
Why was this issue closed?

**Comment by rautamiekka** [comment]
1.8.3 is obsolete.

**Comment by Telbaru** [comment]
in one of the latest builds the error disappears...so i mean that it was a problem with spigot.

**Comment by gerardvanschip** [comment]
I cant load Dynmap-WorldGuard in Spigot 1.8 - 1.8.7 and everything in between. Same error on all.

**Comment by Telbaru** [comment]
what java-version do you use?

**Comment by gerardvanschip** [comment]
My host uses Java 7, I can submit a ticket for 8. Which one is needed?

**Comment by Telbaru** [comment]
i'm using 1.8 and it works perfectly...is it possible that an other plugin makes the problems? is your dynmap up to date?
