### ISSUE TITLE
NullPointerException, not sure wether D-WG is the main problem or not

### ISSUE THREAD

**Issue by HanatakeYurii** [webbukkit/Dynmap-WorldGuard#33]
Hi,

I'm managing a server for a long time and I got problems with launching Dynmap-WorldGuard since I updated all my plugins and Spigot to the latests versions for MC 1.8.8 (at least for now).
Everytime I try to run my server with D-WG it throw a critical error that cause the server to restart:

[16:06:43] [Server thread/WARN]: [Dynmap-WorldGuard] Task #243 for Dynmap-WorldGuard v0.80 generated an exception
java.lang.NullPointerException: The world was unloaded and the reference is unavailable
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getWorld(BukkitWorld.java:131) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getName(BukkitWorld.java:149) ~[?:?]
	at com.sk89q.worldedit.Location.toString(Location.java:110) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.formatInfoWindow(DynmapWorldGuardPlugin.java:128) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.handleRegion(DynmapWorldGuardPlugin.java:290) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.access$100(DynmapWorldGuardPlugin.java:44) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:351) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

For more explanations, the server runs, launches plugins until D-WG where it loads firsts worlds then throw that exception and restart again. Until the error the dynmap is loading well with all regions marked. The servers runs without errors with D-WG deactivated (or removed, as you wish).

I'm not really sure if it's an D-WG error or a side-effect to a possibly misleading file in MultiVerse that try to load missing worlds or something like that.

If someone have an idea, please let me know.

**Comment by HanatakeYurii** [comment]
Hi,

Having the same error since. 

After investigating, that NPE seems linked to WorldGuard and MultiVerse as DW tries to load regions from a world that doesn't exist anymore. 

Hope that will help
