### ISSUE TITLE
Support for 1.13 (Spigot)

### ISSUE THREAD

**Issue by pavelGR83** [webbukkit/Dynmap-WorldGuard#44]
[17:59:08] [Server thread/INFO]: [Dynmap-WorldGuard] Enabling Dynmap-WorldGuard v0.90
[17:59:08] [Server thread/INFO]: [Dynmap-WorldGuard] initializing
[17:59:08] [Server thread/ERROR]: Error occurred while enabling Dynmap-WorldGuard v0.90 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getProfileCache()Lcom/sk89q/worldguard/util/profile/cache/ProfileCache;
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.onEnable(DynmapWorldGuardPlugin.java:390) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [craftbukkit.jar:git-Spigot-2b0e71c-15da706]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by PlasmaPod** [comment]
Please update we heavily rely on this plugin

**Comment by mikeprimm** [comment]
Updated - beta-2 was supported by 1.1-alpha-2 release, and beta-3 is now supported by 1.1-beta-3 release
