### ISSUE TITLE
exception java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by kaiarne** [webbukkit/Dynmap-WorldGuard#45]
Plugin did fine until this week. Since Nov. 7th we are getting this exception on startup:

`[11:21:39] [Server thread/WARN]: [Dynmap-WorldGuard] Task #347 for Dynmap-WorldGuard v1.1-alpha-1 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedRegion.getMinimumPoint()Lcom/sk89q/worldedit/BlockVector;
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.handleRegion(DynmapWorldGuardPlugin.java:247) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.access$200(DynmapWorldGuardPlugin.java:48) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:356) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-2474d93-ca22de3]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
`

This appeared first between this version combination:
GOOD: git-Spigot-2474d93-e693496 + worldguard v7.0.0-SNAPSHOT;1753-0dc5781    
BAD: git-Spigot-2474d93-ca22de3+ worldguard v7.0.0-SNAPSHOT;1754-9169653

**Comment by kaiarne** [comment]
I tried to fix this issue here: https://github.com/kaiarne/Dynmap-WorldGuard/commit/c1ff705e34541a65e1ce68b0a0b4e909e7666706
Though I'm not entirely sure what I was doing :) it's working for us now again.

**Comment by Lice2** [comment]
I have the same problem but I use worldguard v7.0.0-SNAPSHOT; 1756

**Comment by mikeprimm** [comment]
beta-2 was fixed by 1.1-alpha-2, and beta-3 was just fixed by 1.1-beta-3.   The WG code doesn't have a stable API I can count on, so tracking and supporting SNAPSHOT churn isn't really practical for me...
