### ISSUE TITLE
worldguard-legacy-7.0.0-beta-03

### ISSUE THREAD

**Issue by Lice2** [webbukkit/Dynmap-WorldGuard#49]
[14:23:19] [Server thread/WARN]: [Dynmap-WorldGuard] Task #71 for Dynmap-WorldGuard v1.1-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
	at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:313) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by ThEWiZ76** [comment]
I have the same issue, but my exception is a bit different, hope this helps:
```
[14:15:31 WARN]: [Dynmap-WorldGuard] Task #10 for Dynmap-WorldGuard v1.1-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
        at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:313) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-493]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-493]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1002) ~[patched_1.13.2.jar:git-Paper-493]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-493]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-493]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-493]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by MrSpock78** [comment]
https://github.com/kaiarne/Dynmap-WorldGuard
This fork already fixed it.

**Comment by ThEWiZ76** [comment]
thnx! I'll give it a try!

**Comment by ThEWiZ76** [comment]
Works like a charm, thnx @MrSpock78

**Comment by mikeprimm** [comment]
Official release with update for WG 7.0.0-beta-3 released (thanks to @wizjany for the update!)
