### ISSUE TITLE
WorldGuard 7.0.0 Beta 3 (MC 1.13+ ONLY!) 

### ISSUE THREAD

**Issue by Lice2** [webbukkit/Dynmap-WorldGuard#50]
Hello Unfortunately, it still does not work for me!
Here is the download link from the Bukkit site where I downloaded the beta 3.
https://dev.bukkit.org/projects/worldguard/files/2663455/download

Sorry that I am preparing so many circumstances!

[18:47:04] [Server thread/WARN]: [Dynmap-WorldGuard] Task #71 for Dynmap-WorldGuard v1.1 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.WorldGuard.getProfileCache()Lcom/sk89q/squirrelid/cache/ProfileCache;
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.formatInfoWindow(DynmapWorldGuardPlugin.java:116) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.handleRegion(DynmapWorldGuardPlugin.java:284) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin.access$100(DynmapWorldGuardPlugin.java:45) ~[?:?]
	at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:350) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by seema84** [comment]
@mikeprimm 
the build v1.1-beta-3 dont work with we beta 5 and wg beta 3
