### ISSUE TITLE
Works on Spigot 1.16.2, fails on Spigot 1.16.3

### ISSUE THREAD

**Issue by Mintaka3a** [webbukkit/Dynmap-WorldGuard#62]
Error in log file during startup after upgrading to Spigot 1.16.3:

[Server thread/ERROR]: Error occurred while enabling Dynmap-WorldGuard v1.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at org.dynmap.bukkit.DynmapPlugin.getMarkerAPI(DynmapPlugin.java:1042) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.activate(DynmapWorldGuardPlugin.java:422) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.onEnable(DynmapWorldGuardPlugin.java:394) ~[?:?]
[snip]

Roll back to 1.16.2 and the plugin functions perfectly again.

**Comment by seema84** [comment]
more information is needed (dynmap version, spigot build)
the problem still exists?
